### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
Feel free to add your own versions of the patches ;). Also, even with these patches it doesn't work for me. Is your C2 booting with it?

**Comment by xypron** [comment]
Hello Jochen (@jspricke),

thank you for indicating that I incorrectly recreated the patches by Heiner Kallweit. The new files were missing. I want the patches to match the patches by Heiner as closely as possible for resubmission to the U-Boot list.

I have pulled your third patch.

I do not want to change the Makefile. I need to be able to test the different build steps separately. In the Makefile U-Boot is already built in parallel (make -j6).

Best regards

Heinrich Schuchardt

**Comment by jspricke** [comment]
`all: prepare build fip_create sign`

means: make can run all dependencies in any order or parallel. Try a make -j6 in the main repo to see the problem ;). You can still run each step separately with my patch. Would be great, if you could include it.

**Comment by xypron** [comment]
@jspricke 

With your patch target sign will always invoke fip-create, build, and prepare. I am not able to run sign separately. This is due to the fact that there is no

    touch fip-create

http://pubs.opengroup.org/onlinepubs/007904975/utilities/make.html
specifies:
"The make utilities in most historical implementations process the prerequisites of a target in left-to-right order, and the makefile format requires this."

**Pull request closed without merging**
